#!/bin/bash

# SSL
sudo snap install core; sudo snap refresh core
sudo apt remove certbot
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --nginx -d "$domain"
sudo systemctl status snap.certbot.renew.service

